GET https://fooderra-api.vercel.app/api/users/details
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwiaWQiOiI2NWFkMmZiN2Q1NDQzZmQ2MzBjODFlODAiLCJpYXQiOjE3MDU4NTA2MTksImV4cCI6MTcwNTg1NDIxOX0.eZ95sjm_YA-pecxqzfbs6VsORO5-gh7T1uWmr4e51ws