GET https://fooderra-api.vercel.app/api/users/details
Content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImF6aXpAZ21haWwuY29tIiwiaWQiOiI2NWFkNGJiYjczZWE4YjFiMmNmMThiYTEiLCJpYXQiOjE3MDU5MTA2MDUsImV4cCI6MTcwNTkxNDIwNX0.etDE6FIBNmPbd6bfMG6cY0eE0LfR7MoIZQaLEu72Sx8